import { ProductCardProps } from '../../HOC/hooks/type';

export const products: ProductCardProps[] = [
  {
    title: 'Classic Leather Chair',
    price: 249,
    rating: 4,
    isNew: true,
    salePercentage: 15,
  },
  {
    title: 'Modern Wooden Table',
    price: 499,
    rating: 4,
    isNew: false,
    salePercentage: 0,
  },
  {
    title: 'Minimal Floor Lamp',
    price: 129,
    rating: 4,
    isNew: true,
    salePercentage: 10,
  },
  {
    title: 'Fabric Sofa 3-Seater',
    price: 899,
    rating: 4,
    isNew: false,
    salePercentage: 20,
  },
  {
    title: 'Marble Coffee Table',
    price: 349,
    rating: 4,
    isNew: false,
    salePercentage: 5,
  },
  {
    title: 'Oak Bookshelf',
    price: 299,
    rating: 4,
    isNew: true,
    salePercentage: 0,
  },
  {
    title: 'Scandinavian Desk',
    price: 579,
    rating: 4,
    isNew: false,
    salePercentage: 12,
  },
  {
    title: 'Velvet Accent Chair',
    price: 219,
    rating: 4,
    isNew: true,
    salePercentage: 8,
  },
  {
    title: 'Industrial Bar Stool',
    price: 149,
    rating: 4.0,
    isNew: false,
    salePercentage: 0,
  },
  {
    title: 'Rattan Lounge Chair',
    price: 329,
    rating: 4,
    isNew: false,
    salePercentage: 18,
  },
  {
    title: 'Glass Side Table',
    price: 179,
    rating: 4,
    isNew: true,
    salePercentage: 0,
  },
  {
    title: 'Upholstered Bed Frame',
    price: 1099,
    rating: 4,
    isNew: false,
    salePercentage: 25,
  },
  {
    title: 'Wall Mounted Shelf',
    price: 89,
    rating: 4,
    isNew: true,
    salePercentage: 0,
  },
  {
    title: 'Ceramic Table Lamp',
    price: 139,
    rating: 4,
    isNew: false,
    salePercentage: 7,
  },
  {
    title: 'Outdoor Patio Chair',
    price: 199,
    rating: 4,
    isNew: false,
    salePercentage: 10,
  },
];
