cacheFolder: .yarn

injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.development?
  - .env.production?

nodeLinker: node-modules

npmAlwaysAuth: true
npmAuthToken: '${CI_SERVICE_REPOSITORY_TOKEN}'
npmRegistryServer: '${CI_SERVICE_REPOSITORY_NPM_PUBLIC_URL}'

npmScopes:
  haibazo:
    npmAlwaysAuth: true
    npmAuthToken: '${CI_SERVICE_REPOSITORY_TOKEN}'
    npmPublishRegistry: '${CI_SERVICE_REPOSITORY_NPM_RELEASE_URL}'

yarnPath: .yarn/releases/yarn-4.9.4.cjs
