# Specify the folder where Yarn should store its cache files
cacheFolder: .yarn

# Define the method Yarn should use to link node modules
nodeLinker: node-modules

# Configuration for npm scopes
npmScopes:
  haibazo:
    # Always authenticate when accessing the npm registry for this scope
    npmAlwaysAuth: true
    # URL of the npm registry for publishing packages
    npmPublishRegistry: ${CI_SERVICE_REPOSITORY_NPM_RELEASE_URL}
    # Authentication token for the npm registry, this token only has read access, so it can be shared
    # If you need to publish packages, you should use your own token, which has write access, and keep it secret
    npmAuthToken: ${CI_SERVICE_REPOSITORY_TOKEN}

# Always authenticate when accessing the npm registry for this scope
npmAlwaysAuth: true

# URL of the npm registry for installing packages
npmRegistryServer: ${CI_SERVICE_REPOSITORY_NPM_RELEASE_URL}

# Authentication token for the npm registry, this token only has read access, so it can be shared
# If you need to publish packages, you should use your own token, which has write access, and keep it secret
npmAuthToken: ${CI_SERVICE_REPOSITORY_TOKEN}

# Specify the path to the Yarn binary
yarnPath: .yarn/releases/yarn-4.5.0.cjs

# Inject environment files
injectEnvironmentFiles:
  [
    '.env?',
    '.env.local?',
    '.env.development?',
    '.env.production?',
  ]