# core
sonar.projectKey=its-c_phucth_its-phucth-component_77c0aa25-5d97-4dc7-a25d-c19fab6fe902
sonar.qualitygate.wait=true

# analysis scope
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/generated/**,**/*.min.js,**/*.css
sonar.test.exclusions=**/e2e/**,**/it/**