export const categories = [
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Coat Collection',
  'Summer Collection',
  'Summer Collection',
  'Summer Collection',
  'Summer Collection',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Home & Decor',
  'Clothing',
  'Accessories',
  'Outdoor',
  'Accessories',
  'Outdoor',
  'Accessories',
  'Outdoor',
];
